#usuario: arleswasb
#senha: 123456
#repositório: top-pet
#dockerhub: arleswasb/top-pet
#docker-compose:
#chave acesso 850b5842543d3c56cbfaf3f0b44027a2fe4c625e

#cliente1
#chave acesso 0b92a820a05247d1815b5c06c1cb0c803f6cd8c7



version: '3.8'
services:
  web:
    build: ./backend
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"

    environment:
    environment:
      - DJANGO_SETTINGS_MODULE=yourproject.settings
      - PYTHONUNBUFFERED=1
    
    # ---------------------------
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: top_pet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d top_pet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  media_data: