
# docker-compose.yml

version: '3.8'
services:
  web:
    build: ./backend
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    # --- ADICIONE ESTA LINHA ---
    env_file:
      - ./.env
    # ---------------------------
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: top_pet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d top_pet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  media_data: