
# docker-compose.yml

version: '3.8' # Pode remover esta linha se quiser
services:
  web:
    build: ./backend
    # REMOVA A LINHA ABAIXO, pois o comando já está no Dockerfile
    # command: /app/entrypoint.sh 
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    environment: # Esta seção é lida pelo settings.py
      POSTGRES_NAME: top_pet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: top_pet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d top_pet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  media_data: