#usuario: arleswasb
#senha: 123456
#repositório: top-pet
#dockerhub: arleswasb/top-pet
#docker-compose:



services:
  web:
    build: ./backend
    command: /app/entrypoint.sh
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    # --- ADICIONE ESTA SEÇÃO ---
    environment:
      POSTGRES_NAME: top_pet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    # ---------------------------
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: top_pet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d top_pet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  media_data: