# Use uma imagem base do Python
FROM python:3.9-slim

# Define variáveis de ambiente
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Define o diretório de trabalho
WORKDIR /app

# Copia e instala as dependências
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copia o resto do código da aplicação
COPY . /app/

# Copia o entrypoint e dá permissão de execução
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Define o entrypoint a ser executado sempre que o contêiner iniciar
ENTRYPOINT ["/app/entrypoint.sh"]

# Define o comando PADRÃO a ser executado pelo entrypoint
# Este comando será usado pelo 'docker compose up'
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]