# Generated by Django 5.2.3 on 2025-07-04 22:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('especie', models.CharField(max_length=50, verbose_name='Espécie')),
                ('raca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea'), ('DESCONHECIDO', 'Desconhecido')], default='DESCONHECIDO', max_length=15, verbose_name='Sexo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets_photos/', verbose_name='Foto do Pet')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'indexes': [models.Index(fields=['tutor'], name='pet_tutor_idx'), models.Index(fields=['especie'], name='pet_especie_idx'), models.Index(fields=['raca'], name='pet_raca_idx')],
            },
        ),
    ]
