# Generated by Django 4.2.21 on 2025-06-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
            ],
        ),
    ]
