# Generated by Django 4.2.23 on 2025-06-23 04:26

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_pet_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='idade',
        ),
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado Em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Adicionais'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea'), ('DESCONHECIDO', 'Desconhecido')], default='DESCONHECIDO', max_length=15, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(max_length=50, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pets_photos/', verbose_name='Foto do Pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Tutor'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['tutor'], name='pet_tutor_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['especie'], name='pet_especie_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['raca'], name='pet_raca_idx'),
        ),
    ]
