# Generated by Django 5.2.3 on 2025-06-27 14:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Consulta')),
                ('tipo_consulta', models.CharField(choices=[('ROTINA', 'Consulta de Rotina'), ('EMERGENCIA', 'Emergência'), ('RETORNO', 'Retorno'), ('EXAME', 'Exame'), ('CIRURGIA', 'Cirurgia'), ('VACINA', 'Vacinação')], default='ROTINA', max_length=20, verbose_name='Tipo de Consulta')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Peso (kg)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('35.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))], verbose_name='Temperatura (°C)')),
                ('motivo_consulta', models.TextField(help_text='Descreva o motivo da consulta', verbose_name='Motivo da Consulta')),
                ('exame_fisico', models.TextField(blank=True, help_text='Descrição do exame físico realizado', verbose_name='Exame Físico')),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico médico', verbose_name='Diagnóstico')),
                ('tratamento', models.TextField(blank=True, help_text='Descrição do tratamento prescrito', verbose_name='Tratamento')),
                ('medicamentos', models.TextField(blank=True, help_text='Lista de medicamentos prescritos', verbose_name='Medicamentos')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', verbose_name='Observações')),
                ('proxima_consulta', models.DateTimeField(blank=True, help_text='Data da próxima consulta (se aplicável)', null=True, verbose_name='Próxima Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='pets.pet', verbose_name='Pet')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios_veterinario', to=settings.AUTH_USER_MODEL, verbose_name='Veterinário')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'ordering': ['-data_consulta'],
            },
        ),
    ]
