# Generated by Django 4.2.23 on 2025-06-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prontuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='veterinario',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='veterinario',
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.DeleteModel(
            name='Prontuario',
        ),
        migrations.DeleteModel(
            name='Vacina',
        ),
    ]
