# Generated by Django 5.2.3 on 2025-06-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crmv',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CRMV'),
        ),
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='profile',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FUNCIONARIO', 'Funcionário'), ('VETERINARIO', 'Veterinário'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=50),
        ),
    ]
