# Generated by Django 4.2.22 on 2025-06-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_pet_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('servico', models.CharField(choices=[('BANHO_E_TOSA', 'Banho e Tosa'), ('CONSULTA', 'Consulta'), ('VACINACAO', 'Vacinação'), ('EXAME', 'Exame')], max_length=50)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pets.pet')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
    ]
