name: CI Pipeline - Lint e Testes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: "Análise de Código (Pylint)"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-django django djangorestframework
          pip install -r backend/requirements.txt
          
      - name: Executar Pylint no backend
        run: |
          cd backend
          pylint --errors-only $(find . -name "*.py" -not -path "./venv/*" -not -path "./__pycache__/*" -not -path "./migrations/*")
        continue-on-error: false
        
      - name: Relatório de Pylint (informativo)
        run: |
          cd backend
          pylint --errors-only $(find . -name "*.py" -not -path "./venv/*" -not -path "./__pycache__/*" -not -path "./migrations/*") || true
        continue-on-error: true

  tests:
    name: "Execução de Testes"
    runs-on: ubuntu-latest
    needs: lint  # Executa após o lint passar
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: Configurar banco de dados de teste
        run: |
          cd backend
          python manage.py migrate --settings=top_pet.settings
          
      - name: Executar testes do Django
        run: |
          cd backend
          python manage.py test --verbosity=2 --keepdb
        env:
          DJANGO_SETTINGS_MODULE: top_pet.settings
          
      - name: Executar testes de unidade (pets)
        run: |
          cd backend
          python manage.py test pets.tests_unidade --verbosity=2
        continue-on-error: false
        
      - name: Executar testes de integração (agendamentos)
        run: |
          cd backend
          python manage.py test agendamentos.tests_integracao --verbosity=2
        continue-on-error: false
        
      - name: Relatório de cobertura de testes
        run: |
          cd backend
          echo "✅ Testes executados com sucesso!"
          echo "📊 Apps testados:"
          echo "  - pets: testes de unidade"
          echo "  - agendamentos: testes de integração"
          echo "  - users: testes básicos"
          echo "  - prontuarios: testes básicos"